### ISSUE TITLE
Cannot reconnect streamer through repeater

### ISSUE THREAD

**Issue by ItsNickBarry** [pulviscriptor/agario-devtools#2]
I have modified example.js from agario-client to use this line, instead of the getAgarioServer function:

```
client.connect("ws://127.0.0.1:9158/","");
```

I run repeater.js, connect a viewer, and then run example.js.  The repeater functions properly, and I can view the bot's actions in the browser.

If I restart example.js, it cannot reconnect, and gives this output:

```
worker: client created
worker: [warning] You did not specified "key" for Client.connect(server, key)          If server will not accept you, this may be the problem
worker: connecting...
worker: connected to server
worker: disconnected
```

I see that it wants me to specify a key, but why does it work on the first connect but not the second?  This message appears even on successful connects.

**Comment by pulviscriptor** [comment]
This one is tricky.

> why does it work on the first connect but not the second?

Before 21.06.2015 repeater was requesting server on startup and then connecting to it for every streamer. 
But then keys was introduced. 
So now repeater requesting server and key and then connecting to it. But you can not connect twice with same key, so that's why on second time server disconnects you after streamer sends used key.

My solution will be to request new server and key for every streamer connection. You will be connecting to random server every time you connect to streamer, but I don't see other solution.
I need to change some logic in both `repeater.js` and `recorder.js`. I will try to do it now, or in next 24 hours.
For now only solution is to restart repeater to get new valid key from server.

> I see that it wants me to specify a key

You need key only for agar.io server. If you connecting to repeater then he will do key magic itself. Ignore this warning.
